version: '3.3'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    networks:
    - testing-network
    ports:
        - 3000:3000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/" ]
      interval: 15s
      timeout: 10s
      retries: 15
  
  robot:
    shm_size: 2gb
    networks:
      - testing-network  
    image: ppodgorsek/robot-framework:latest
    volumes:
      - ${PWD}/robot/out:/opt/robotframework/reports:Z
      - ${PWD}/robot/tests:/opt/robotframework/tests:Z
    depends_on:
      - portfolio
    ports:
        - 3001:3001

networks:
  testing-network:  