version: '3.3'


services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    environment:
      REACT_APP_BACKEND_URL: $REACT_APP_BACKEND_URL
    expose:
      - 3000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/" ]
      interval: 15s
      timeout: 10s
      retries: 15