version: '3.3'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
        - 3000:3000
  
  robot:
    image: ppodgorsek/robot-framework:latest
    volumes:
      - ./robot/out:/opt/robotframework/reports:Z
      - ./robot/tests:/opt/robotframework/tests:Z
    ports:
        - 3001:3001

