
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Build and run frontend container
      run: |
          docker-compose -f docker-compose-start.yaml up -d
    - name: Run tests
      run: |
        docker run --shm-size=2g -e BROWSER=headlesschrome \
        -v ${{ github.workspace }}/robot/tests:/opt/robotframework/tests:Z \
        ppodgorsek/robot-framework:latest
    - name: Clean up
      if: always()
      run: |
        docker compose down