
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      packages: write
    steps:
    - name: test env
      run: echo {$REACT_APP_BACKEND_URL}
    - uses: actions/checkout@v3
    - name: Build and run frontend container
      run: |
          docker-compose -f docker-compose-start.yaml up -d
    - name: Run tests
      run: |
          docker-compose -f docker-compose-test.yaml up
    - name: Clean up
      if: always()
      run: |
        docker compose down