
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Build and run containers
      run: |
          docker compose up
    - name: Clean up
      if: always()
      run: |
        docker compose down